# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-30 06:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hwp_eq', models.CharField(max_length=500)),
                ('latex_eq', models.CharField(max_length=500)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('conversion_ok', models.BooleanField(default=True)),
            ],
        ),
    ]
